name: recipe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  sliding_up_panel: ^2.0.0+1
  tab_indicator_styler: ^2.0.0
  tabler_icons: ^2.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/images/
